
resources:
  repositories:
  - repository: Carpenter
    type: github
    name: suent/carpenter-azure-pipelines
    endpoint: suent

stages:
- template: template/carpenter-default.yml@Carpenter
  parameters:
    pipelineVersion: 1